### ISSUE TITLE
Missing manifest.json file - can't be loaded as Chrome extension

### ISSUE THREAD

**Issue by tomasz-chojna** [muchas/tesco-auto-trolley#1]
<img width="747" alt="screen shot 2017-07-27 at 6 14 15 am" src="https://user-images.githubusercontent.com/1398756/28654223-146ac3ba-7293-11e7-9f70-acec588e90b3.png">

[https://developer.chrome.com/extensions/getstarted](https://developer.chrome.com/extensions/getstarted)

**Comment by muchas** [comment]
Updated __README.md__

https://github.com/muchas/tesco-auto-trolley#installation
